name: Automate STOCK_LIST gh_bot

on:
  push:
  workflow_dispatch:
#  schedule:
    # Asia/Kuala_Lumpur around 6pm, weekdays only
#    - cron: "0 10 * * 1,2,3,4,5"

jobs:
  automation:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [15.3.0]

    steps:
      - uses: actions/checkout@v2
      - name: Syncing with latest branch
        run: |
          git config pull.rebase false
          git pull origin $(git branch --show-current)
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing puppeteer dependencies
        run: sudo apt-get update && sudo apt install chromium-browser
      - run: yarn --frozen-lockfile
      - run: yarn run ghAction:update-data

      - name: Commit changes
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: GitHub Actions Bot
          author_email: <>
          message: "[STOCK_LIST] gh_bot: Update with new changes"
          add: "stock-list.json contents"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
