name: Automate STOCK_LIST gh_bot

on:
  workflow_dispatch:
  schedule:
    # Asia/Kuala_Lumpur around 6pm, weekdays only
    - cron: "0 10 * * 1,2,3,4,5"

jobs:
  automation:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.3.0'

      - run: npm ci
      - run: npm run ghAction:update-data

      - name: Commit changes
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: GitHub Actions Bot
          author_email: <>
          message: "[STOCK_LIST] gh_bot: Update with new changes"
          add: "stock-list.json contents"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
