name: Automate STOCK_LIST gh_bot

on:
  push:
  workflow_dispatch:
#  schedule:
    # Asia/Kuala_Lumpur around 6pm, weekdays only
#    - cron: "0 10 * * 1,2,3,4,5"

jobs:
  automation:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: fix/github-action

      - name: Build & run docker
        run: |
          docker build -t tsi .
          docker run \
           -v $PWD/contents/:/usr/src/app/contents \
           -v $PWD/stock-list.json/:/usr/src/app/stock-list.json \
           tsi

      - name: Commit changes
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: GitHub Actions Bot
          author_email: <>
          message: "[STOCK_LIST] gh_bot: Update with new changes"
          add: "stock-list.json contents"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
