name: [STOCK_LIST] script_bot

on:
  push:
    branches: [ feature/module-scrpit-improvement-and-fixing-bug ]
  pull_request:
    branches: [ feature/module-scrpit-improvement-and-fixing-bug ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run update-data
