name: Automate STOCK_LIST gh_bot

on:
  push:
    branches:
      - lerna-init
  workflow_dispatch:
#  schedule:
#    - cron: "0 10 * * 1,2,3,4,5"
    # Asia/Kuala_Lumpur around 6pm, weekdays only

jobs:
  automation:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.12.0'
      - uses: bahmutov/npm-install@HEAD

      - name: Run script
        run: yarn run ghAction

      - name: Commit changes
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: GitHub Actions Bot
          author_email: <>
          message: "[STOCK_LIST] gh_bot: Update with new changes"
          add: "stock-list.json contents"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
