name: Automate STOCK_LIST gh_bot

on:
  schedule:
    - cron: "0 18 * * *"

jobs:
  automation:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run ghAction:update-data

      - name: Setup git config
        run: git config pull.rebase false

      - name: Commit changes
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: GitHub Actions Bot
          author_email: <>
          message: "[STOCK_LIST] gh_bot: Update with new changes"
          add: "stock-list.json stock-readonly-list.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
